### ISSUE TITLE
npm start ERROR

### ISSUE THREAD

**Issue by dertuerke** [micromata/Baumeister#215]
Hi, i get this error if i run "npm start"

```
[21:09:39] 'copyStaticFiles' errored after 32 ms
[21:09:39] Error: Invalid glob argument: 
    at Gulp.src (project/node_modules/vinyl-fs/lib/src/index.js:32:11)
    at copyStaticFiles (project/gulp/tasks/copyStaticFiles.js:11:14)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (project/node_modules/async-done/index.js:39:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[21:09:39] 'default' errored after 201 ms
[21:09:39] The following tasks did not complete: processHtml, appTemplates, lint, fonts, images, clientScripts, vendorScripts, validateHtml, lintBootstrap, lintStyles, test
[21:09:39] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ivs-region@0.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ivs-region@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```

**Comment by mischah** [comment]
After following the description of #214?

I guess I have an idea …

**Comment by dertuerke** [comment]
@mischah yes after #214

**Comment by dertuerke** [comment]
Fehler gefunden. Das Array darf nicht Leer sein.

So funktioniert es dann ;)
```
"includeStaticFiles": [
   ""
]
```

**Comment by mischah** [comment]
It's a bug. 

Right now `includeStaticFiles` must have at least one item:
https://github.com/micromata/Baumeister/blob/c4029a4f1f5b88733c48ed1c5bf5d1024e237400/baumeister.json#L9-L11

Going to fix this.

**Comment by dertuerke** [comment]
Jetzt kommen folge fehler :S 

Ich schreib dir mal eine Mail :)

**Comment by mischah** [comment]
Fixed.
