### ISSUE TITLE
Instantly fails build after install

### ISSUE THREAD

**Issue by chrisschaetzlein** [micromata/Baumeister#263]
After running the yeoman generator, running `npm run start` fails with the following error:

```
imac:template Chris$ npm run start

> template@0.0.0 start /Users/Chris/Sites/match-iq.com/template
> npm-run-all clean:dev handlebars --parallel handlebars:watch webpack:server eslint:watch stylelint:watch --silent

✔  Finished Handlebars build after 70 ms 

/Users/Chris/Sites/template/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/Chris/Sites/template/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/Users/Chris/Sites/template/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! template@0.0.0 start: `npm-run-all clean:dev handlebars --parallel handlebars:watch webpack:server eslint:watch stylelint:watch --silent`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the template@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Chris/.npm/_logs/2018-10-22T08_50_46_460Z-debug.log
```

Running on NodeJS version 8.11.3 with NPM 6.4.1 on macOS Mojave. Please help!

**Comment by mischah** [comment]
See #264 for a workaround until a proper fix will land.
